# GET http://localhost:3000/user/ex1/123 HTTP/1.1



# GET http://localhost:3000/user/ex2?id=1&ip=9 HTTP/1.1



# GET http://localhost:3000/user/ex3?id=1&ip=9 HTTP/1.1


# POST http://localhost:3000/user/ex4 HTTP/1.1
# Content-Type: application/json

# {
#   "name": "jay",
#   "age": "18",
#   "ip": "9"
# }

# GET http://localhost:3000/user/ex5?id=1&ip=9 HTTP/1.1


GET http://localhost:3000/board/2 HTTP/1.1


# POST http://localhost:3000/user HTTP/1.1
# Content-Type: application/json

# {
#   "name": "user",
#   "age": "20",
#   "email": "user@163.com"
# }


# POST http://localhost:3000/role/query HTTP/1.1
# Content-Type: application/json

# {
#   "name": "user"
# }


# DELETE http://localhost:3000/role HTTP/1.1
# Content-Type: application/json

# {
#   "ids": [5,6]
# }


# POST http://localhost:3000/board HTTP/1.1
# Content-Type: application/json

# {
#   "title": "看板22222",
#   "desc": "测试用22222"
# }



# PUT http://localhost:3000/board HTTP/1.1
# Content-Type: application/json

# {
#   "desc": "测试用111111111?",
#   "cards": [{
#     "id": 4,
#     "title": "卡片1111111111?",
#     "posi": "whxyi",
#     "data": "111啊啊"
#   }, {
#     "title": "卡片333333333333333",
#     "posi": "whxyi",
#     "data": "333",
#     "xxx": "xxx"
#   }]
# }