-- AlterTable
ALTER TABLE `card` ALTER COLUMN `h` DROP DEFAULT,
    ALTER COLUMN `i` DROP DEFAULT,
    ALTER COLUMN `w` DROP DEFAULT,
    ALTER COLUMN `x` DROP DEFAULT,
    ALTER COLUMN `y` DROP DEFAULT;
